[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
swc_atoms = "1.0.0"
swc_compiler_base = "0.23.0"
swc_common = { version = "0.40.0", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.121.0"
swc_ecma_parser = "0.152.0"
parking_lot = "0.12.3"
