[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.88"
swc_atoms = "0.6.7"
swc_compiler_base = "0.21.0"
swc_common = { version = "0.38.0", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.119.0"
swc_ecma_parser = "0.150.0"
parking_lot = "0.12.3"
