[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
swc_atoms = "0.7.0"
swc_compiler_base = "0.22.0"
swc_common = { version = "0.39.0", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.120.0"
swc_ecma_parser = "0.151.0"
parking_lot = "0.12.3"
