[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.91"
swc_atoms = "2.0.0"
swc_compiler_base = "1.0.0"
swc_common = { version = "1.0.0", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "1.0.0"
swc_ecma_parser = "1.0.1"
parking_lot = "0.12.3"
