[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
swc = "0.266.37"
swc_common = "0.32.2"
swc_ecma_ast = "0.109.2"
swc_ecma_parser = "0.140.1"
swc_error_reporters = "0.16.2"
parking_lot = "0.12.1"
swc_ecma_lints = "0.88.9"
swc_ecma_transforms_base = "0.133.8"
swc_ecma_visit = "0.95.2"
