[package]
name = "bindings_wasm"
version = "0.0.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
parse_ast = { path = "../parse_ast" }
xxhash = { path = "../xxhash" }
js-sys = "0.3.69"
getrandom = { version = "0.2.14", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]
