[package]
name = "xxhash"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = '0.21.5'
xxhash-rust = { version = "0.8.8", features = ["xxh3"] }
